feat: communicationRequest to edition File
InseeFr/Pearl-Jam-Batch pull request #71
Opened 2024-10-14 14:07 UTC by SimonDmz

2024-10-17 07:06 UTC, davdarras commented on src/main/java/fr/insee/pearljam/batch/service/impl/CommunicationServiceImpl.java
> +                communicationRequestDao.findAll().stream().filter(cr -> toBeSentStatus.contains(cr.getStatus())).toList();
mutliline for more comprehensive code ?

2024-10-17 07:06 UTC, davdarras commented on src/main/java/fr/insee/pearljam/batch/service/impl/CommunicationServiceImpl.java
> +                        su -> su));
same here

2024-10-17 07:06 UTC, davdarras commented on src/main/java/fr/insee/pearljam/batch/service/impl/CommunicationServiceImpl.java
> +                .collect(Collectors.toSet()).stream().toList();
toList instead of .collect()... ?

2024-10-17 07:06 UTC, davdarras commented on src/main/java/fr/insee/pearljam/batch/service/impl/CommunicationServiceImpl.java
> +        }).toList();
divide this method into smaller parts for more comprehensive code

2024-10-17 07:06 UTC, davdarras commented on src/main/java/fr/insee/pearljam/batch/service/impl/CommunicationServiceImpl.java
> +        String title = person.getTitle().equals("MISS") ? "MME" : "M";
if title is MME ?

2024-10-17 07:06 UTC, davdarras commented on src/main/java/fr/insee/pearljam/batch/service/impl/MeshuggahServiceImpl.java
> +    private final RestTemplate restTemplate;
RestTemplate is deprecated. RestClient maybe ? the re's an implem example on meshuggah

2024-10-17 07:06 UTC, davdarras commented on src/main/java/fr/insee/pearljam/batch/utils/XmlUtils.java
> +			return null;
the exception is swallowed here, need to do something about this

2024-10-22 09:12 UTC, SimonDmz commented on src/main/java/fr/insee/pearljam/batch/Launcher.java
> +			Launcher launcher = context.getBean(Launcher.class);
using Autowired bean in static method is tricky 😢 
=> maybe move static main method in correct class

2024-10-23 14:51 UTC, davdarras commented on src/main/java/fr/insee/pearljam/batch/service/impl/CommunicationServiceImpl.java
> +                        variables.setInitAccuseReception(template.isInitAccuseReception()?"oui":"non");
indent ?

2024-10-23 15:28 UTC, davdarras requested changes

2024-10-23 15:28 UTC, davdarras commented on src/main/java/fr/insee/pearljam/batch/dao/SurveyUnitDaoImpl.java
> +        String qString = """
does it work ?

2024-10-23 15:28 UTC, davdarras commented on src/main/java/fr/insee/pearljam/batch/dao/SurveyUnitDaoImpl.java
> +                SELECT t.id FROM
better indentation maybe ?

2024-10-23 15:28 UTC, davdarras commented on src/main/java/fr/insee/pearljam/batch/dao/SurveyUnitDaoImpl.java
> +                JOIN visibility v ON v.campaign_id=c.id AND su.organization_unit_id=v.organization_unit_id) t
same here

2024-10-25 08:41 UTC, davdarras approved these changes

2024-10-25 08:42 UTC, merged